---
- name: Determine OS distribution name
  set_fact: os_distribution={{ ansible_distribution | lower }}
- debug: var=os_distribution

- name: Determine OS major version
  set_fact: os_major_version={{ ansible_distribution_version.split('.')[0] | lower }}
- debug: var=os_major_version

- include: java8-install-centos-7.yml
  static: no
  when: os_distribution == 'centos' and (ansible_distribution_version | version_compare('7', '>='))
#  when: os_distribution == 'centos' and os_major_version in ['7']

- include: java8-install-ubuntu-14.yml
  static: no
  when: os_distribution == 'ubuntu' and (ansible_distribution_version | version_compare('14', '>='))
#  when: os_distribution == 'ubuntu' and os_major_version in ['14', '16']
